# Generated by Django 6.0.2 on 2026-02-25 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanctionsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sanctions List',
                'verbose_name_plural': 'Sanctions Lists',
            },
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_type', models.CharField(choices=[('SANCTIONS', 'Sanctions Check'), ('PEP', 'PEP Check'), ('ADVERSE_MEDIA', 'Adverse Media')], max_length=20)),
                ('status', models.CharField(choices=[('CLEAR', 'Clear'), ('MATCH', 'Match Found'), ('POTENTIAL_MATCH', 'Potential Match')], max_length=20)),
                ('matched_list', models.CharField(blank=True, max_length=100)),
                ('match_details', models.JSONField(default=dict)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('screened_entity', models.CharField(blank=True, max_length=255)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='merchants.merchant')),
            ],
            options={
                'verbose_name': 'Screening Result',
                'verbose_name_plural': 'Screening Results',
                'ordering': ['-screened_at'],
            },
        ),
    ]
